apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor-helm.fullname" . }}
  labels:
    {{- include "saleor-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "saleor-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "saleor-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "saleor-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.global.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.global.allowedHosts }}
            - name: ALLOWED_CLIENT_HOSTS
              value: {{ .Values.global.allowedHosts }}
          envFrom:
          - secretRef:
              name: saleor-secrets
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              - name: Host
                value: kube-probe
              path: /health/
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 8
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
              - name: Host
                value: kube-probe
              path: /health/
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 8
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
