{{- if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: generated
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
