apiVersion: v1
kind: Secret
metadata:
  name: saleor-secrets
type: Opaque
data:
  EMAIL_URL: {{ .Values.global.emailUrl  | b64enc | quote }}
  SECRET_KEY: {{ .Values.global.secretKey  | b64enc | quote }}
  DATABASE_URL: "{{- printf "postgres://%s:%s@saleor-postgresql:5432/%s"  .Values.global.postgresql.postgresqlUsername .Values.global.postgresql.postgresqlPassword .Values.global.postgresql.postgresqlDatabase | b64enc  -}}"
  ALLOWED_CLIENT_HOSTS: d3d3LnB1bmRmLXRlc3QudHJpZWJ3b3JrLmNvbSx3d3cucHVuZGYtdGVzdC50cmllYndvcmsuZGU=